# Generated by Django 5.1.2 on 2024-11-09 14:15

import author.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(4), author.validators.validate_letters])),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2), author.validators.validate_letters])),
                ('passcode', models.CharField(max_length=6, validators=[author.validators.validate_digits])),
                ('pets_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('info', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
            ],
        ),
    ]
